/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExperimentGUI.java
 *
 * Created on Dec 3, 2010, 12:48:43 PM
 */
package uk.ac.abdn.csd.stereos.gui;

import uk.ac.abdn.csd.stereos.RunExperiment;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import uk.ac.abdn.csd.stereos.exceptions.InvalidParametersException;

/**
 *
 * @author cburnett
 */
public class ExperimentGUI extends javax.swing.JFrame {

    /** Creates new form ExperimentGUI */
    public ExperimentGUI() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        profilesField = new javax.swing.JTextField();
        experimentNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        teamCountField = new javax.swing.JTextField();
        teamSizeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teamLifeTimeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        trusteeSwapProbField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        trustorSwapProbField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        interactProbField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        missingFeatProbField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        maxMissingFeatsField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        noiseFeatureCountField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        visualiserButton = new javax.swing.JToggleButton();
        runButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        experimentStatusField = new javax.swing.JTextArea();
        clusterCountField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        learningIntervalField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gg = new javax.swing.JCheckBox();
        ag = new javax.swing.JCheckBox();
        aa = new javax.swing.JCheckBox();
        aas = new javax.swing.JCheckBox();
        ags = new javax.swing.JCheckBox();
        ggs = new javax.swing.JCheckBox();
        specialConditionsField = new javax.swing.JComboBox();
        failurePayoffField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        successPayoffField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        repFilterButton = new javax.swing.JToggleButton();
        timeStepsField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        failureToDelegatePayoffField = new javax.swing.JTextField();
        monitoringCostField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        decisionModelField = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        connectednessField = new javax.swing.JTextField();
        subDelButton = new javax.swing.JToggleButton();
        visibilityCombo = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Profiles:");

        profilesField.setText("experiment");

        experimentNameField.setText("experiment");

        jLabel2.setText("Experiment Label:");

        jLabel3.setText("Group Count:");

        teamCountField.setText("10");

        teamSizeField.setText("20");

        jLabel4.setText("Group Size:");

        teamLifeTimeField.setText("5");

        jLabel5.setText("Group Lifetime:");

        trusteeSwapProbField.setText("0.0");

        jLabel6.setText("Trustee Swap Prob.:");

        trustorSwapProbField.setText("0.0");

        jLabel7.setText("Trustor Swap Prob.:");

        interactProbField.setText("0.8");

        jLabel8.setText("Interact Prob.:");

        missingFeatProbField.setText("0.0");

        jLabel9.setText("Max. Missing Feats:");

        maxMissingFeatsField.setText("6");

        jLabel10.setText("# Noise Features:");

        noiseFeatureCountField.setText("6");

        jLabel11.setText("Missing Feat. Prob:");

        visualiserButton.setText("Visualiser");
        visualiserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualiserButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        experimentStatusField.setColumns(20);
        experimentStatusField.setRows(2);
        jScrollPane1.setViewportView(experimentStatusField);

        clusterCountField.setText("4");

        jLabel12.setText("Cluster Count:");

        learningIntervalField.setText("20");

        jLabel13.setText("Learning Interval:");

        gg.setSelected(true);
        gg.setText("GG");
        gg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ggActionPerformed(evt);
            }
        });

        ag.setText("AG");

        aa.setText("AA");

        aas.setText("AAS");

        ags.setText("AGS");
        ags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agsActionPerformed(evt);
            }
        });

        ggs.setText("GGS");
        ggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ggsActionPerformed(evt);
            }
        });

        specialConditionsField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "normal", "nocorr", "crash", "mix", "amnesia", "bias" }));

        failurePayoffField.setText("-1");

        jLabel15.setText("Failure Payoff:");

        successPayoffField.setText("12");

        jLabel16.setText("Success Payoff:");

        loadButton.setText("Load...");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save...");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        repFilterButton.setText("Anti-bias Filter");
        repFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repFilterButtonActionPerformed(evt);
            }
        });

        timeStepsField.setText("500");

        jLabel17.setText("Time Steps:");

        jLabel18.setText("Abstain Payoff:");

        failureToDelegatePayoffField.setText("0");
        failureToDelegatePayoffField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                failureToDelegatePayoffFieldActionPerformed(evt);
            }
        });

        monitoringCostField.setText("1.5");
        monitoringCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitoringCostFieldActionPerformed(evt);
            }
        });

        jLabel19.setText("Monitoring Cost:");

        decisionModelField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mosttrusted", "basic", "monitoring", "ri", "meta" }));

        jLabel14.setText("Decision Model:");

        jLabel20.setText("Special Condition:");

        jLabel21.setText("Connectedness:");

        connectednessField.setText("1");
        connectednessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectednessFieldActionPerformed(evt);
            }
        });

        subDelButton.setText("Sub-delegation");
        subDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDelButtonActionPerformed(evt);
            }
        });

        visibilityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "next", "full" }));
        visibilityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilityComboActionPerformed(evt);
            }
        });

        jLabel22.setText("Visibility:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel21)
                        .add(18, 18, 18)
                        .add(connectednessField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 248, Short.MAX_VALUE)
                        .add(repFilterButton)
                        .add(18, 18, 18)
                        .add(subDelButton))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(experimentNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(profilesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel4)
                            .add(jLabel3))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, teamCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, teamSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, teamLifeTimeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 71, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(trusteeSwapProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel7)
                                    .add(jLabel8))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(interactProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(trustorSwapProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 63, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                                .add(missingFeatProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                                .add(maxMissingFeatsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(noiseFeatureCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(visualiserButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(runButton))
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel16)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(successPayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(learningIntervalField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(94, 94, 94)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel12)
                            .add(jLabel15))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, clusterCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, failurePayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(53, 53, 53)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel18)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(failureToDelegatePayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel19)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(monitoringCostField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(gg)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(ag)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(aa)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ggs)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(ags)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(aas))
                            .add(layout.createSequentialGroup()
                                .add(loadButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(saveButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                                .add(jLabel20)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(specialConditionsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(decisionModelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel22)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(visibilityCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(timeStepsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(experimentNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(profilesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(teamCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(teamSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(teamLifeTimeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(trusteeSwapProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(trustorSwapProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(noiseFeatureCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(maxMissingFeatsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(missingFeatProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(interactProbField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel13)
                        .add(learningIntervalField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(clusterCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel12))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(failureToDelegatePayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel18)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel16)
                        .add(successPayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(monitoringCostField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel19))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(failurePayoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel15)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel21)
                            .add(connectednessField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(subDelButton)
                            .add(repFilterButton))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loadButton)
                    .add(saveButton)
                    .add(decisionModelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(jLabel20)
                    .add(specialConditionsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(gg)
                    .add(ag)
                    .add(aa)
                    .add(ggs)
                    .add(ags)
                    .add(timeStepsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(aas)
                    .add(visibilityCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(runButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(visualiserButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualiserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualiserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualiserButtonActionPerformed

    private void ggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ggActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ggActionPerformed

    private void ggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ggsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ggsActionPerformed

    private void agsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agsActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed

    /**
     * This method is called when the run button is clicked. Essentially it just makes
     * a properties file from the parameters given and then calls the RunExperiment
     * class with the proper command line. Should do some validation.
     * @param evt
     */
    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed

        Properties properties = writePropertiesFile();
        boolean visualiser = this.visualiserButton.isSelected();

        // now run...
        this.experimentStatusField.append("Running...\n");
        RunExperiment experimentRunner = new RunExperiment(properties, visualiser, this.experimentStatusField);
        new Thread(experimentRunner).start();


    }//GEN-LAST:event_runButtonActionPerformed

    private Properties writePropertiesFile()
    {
        Properties properties = new Properties();

        properties.put("mode", this.specialConditionsField.getSelectedItem());

        // set rep filtering
        if (this.repFilterButton.isSelected()) {
            properties.put("filter", "antibias");
        } else {
            properties.put("filter", "off");
        }

        // check if sub-delegation desired
        if (this.subDelButton.isSelected())
            properties.put("isSubDelegationAllowed", "yes");
        else
            properties.put("isSubDelegationAllowed", "no");

        properties.put("decisionModel", this.decisionModelField.getSelectedItem());

        properties.put("runs", "1");
        properties.put("profiles", this.profilesField.getText());
        properties.put("teamCount", this.teamCountField.getText());
        properties.put("teamSize", this.teamSizeField.getText());
        properties.put("teamLifeTime", this.teamLifeTimeField.getText());
        properties.put("maxConcurrentMembership", this.connectednessField.getText());
        properties.put("timeSteps", this.timeStepsField.getText());
        properties.put("agentReplaceProb", this.trusteeSwapProbField.getText());
        properties.put("trustorReplaceProb", this.trustorSwapProbField.getText());
        properties.put("interactProb", this.interactProbField.getText());
        properties.put("visibility", this.visibilityCombo.getSelectedItem());

        javax.swing.JCheckBox[] conditionChecks = {gg, ag, aa, ggs, ags, aas};

        StringBuilder conditionString = new StringBuilder();
        boolean b = false;
        for (int i = 0; i < conditionChecks.length; i++) {
            if (conditionChecks[i].isSelected()) {
                if (b) {
                    conditionString.append(",");
                }
                conditionString.append(i + 1);
                b = true;
            }
        }
        properties.put("conditions", conditionString.toString());

        properties.put("noiseFeatureCount", this.noiseFeatureCountField.getText());
        properties.put("maxMissingFeatures", this.maxMissingFeatsField.getText());
        properties.put("missingFeatureProb", this.missingFeatProbField.getText());
        properties.put("learningInterval", this.learningIntervalField.getText());
        properties.put("clusterCount", this.learningIntervalField.getText());
        properties.put("successPayoff", this.successPayoffField.getText());
        properties.put("failurePayoff", this.failurePayoffField.getText());
        properties.put("failToDelegatePayoff", this.failureToDelegatePayoffField.getText());
        properties.put("monitoringCost", this.monitoringCostField.getText());

        // properties we don't care about but will set anyway
        properties.put("temperature", "0.2");
        properties.put("halfLife", "50");
        properties.put("maxQueries", "20");

        // now basically write the file to the experiments directory
        String experimentName = this.experimentNameField.getText();
        properties.put("experimentName", experimentName);
        String parametersPath = "experiments/" + experimentName + ".properties";

        try {
            FileOutputStream out = new FileOutputStream(parametersPath);
            properties.store(out, "Stereotypical Trust Experimental Properties File");
        } catch (IOException ex) {
            Logger.getLogger(ExperimentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        return properties;
    }

    private void repFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repFilterButtonActionPerformed
    }//GEN-LAST:event_repFilterButtonActionPerformed

    private void failureToDelegatePayoffFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_failureToDelegatePayoffFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_failureToDelegatePayoffFieldActionPerformed

    private void monitoringCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitoringCostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monitoringCostFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        writePropertiesFile();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void connectednessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectednessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectednessFieldActionPerformed

    private void subDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subDelButtonActionPerformed

    private void visibilityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visibilityComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExperimentGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aa;
    private javax.swing.JCheckBox aas;
    private javax.swing.JCheckBox ag;
    private javax.swing.JCheckBox ags;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField clusterCountField;
    private javax.swing.JTextField connectednessField;
    private javax.swing.JComboBox decisionModelField;
    private javax.swing.JTextField experimentNameField;
    private javax.swing.JTextArea experimentStatusField;
    private javax.swing.JTextField failurePayoffField;
    private javax.swing.JTextField failureToDelegatePayoffField;
    private javax.swing.JCheckBox gg;
    private javax.swing.JCheckBox ggs;
    private javax.swing.JTextField interactProbField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField learningIntervalField;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField maxMissingFeatsField;
    private javax.swing.JTextField missingFeatProbField;
    private javax.swing.JTextField monitoringCostField;
    private javax.swing.JTextField noiseFeatureCountField;
    private javax.swing.JTextField profilesField;
    private javax.swing.JToggleButton repFilterButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox specialConditionsField;
    private javax.swing.JToggleButton subDelButton;
    private javax.swing.JTextField successPayoffField;
    private javax.swing.JTextField teamCountField;
    private javax.swing.JTextField teamLifeTimeField;
    private javax.swing.JTextField teamSizeField;
    private javax.swing.JTextField timeStepsField;
    private javax.swing.JTextField trusteeSwapProbField;
    private javax.swing.JTextField trustorSwapProbField;
    private javax.swing.JComboBox visibilityCombo;
    private javax.swing.JToggleButton visualiserButton;
    // End of variables declaration//GEN-END:variables
}
